package main.yurtrehberi.yourmovies.Network.Client;

import java.util.Random;

import main.yurtrehberi.yourmovies.Network.Constants.ApiConstants;
import main.yurtrehberi.yourmovies.Network.Service.IMovieService;
import retrofit.RestAdapter;

/**
 * Created by gokhan on 1/19/15.
 */
public class MovieClient {

    private static IMovieService _movieService;

    public static IMovieService getWeather() {
        RestAdapter restAdapter = new RestAdapter.Builder().setLogLevel(RestAdapter.LogLevel.FULL)
                .setEndpoint(ApiConstants.APIURL)
                .build();
        _movieService = restAdapter.create(IMovieService.class);

        return _movieService;
    }

    public static String getRandomMovie() {
        String randomMovie = null;
        Random random = new Random();
        String[] movies = {"ASSASSINS", "BACHELORETTE", "BACK TO THE FUTURE",
                "BAD COUNTRY", "BAD SANTA", "BAD TEACHER", "BLIZZARD",
                "DAYS", "GHOSTS", "GOING ON", "INS",
                "MINUTES", "AGAIN", "YEARS OF ALCOHOL", "BLOWN AWAY", "LOVER COME BACK", "MACHETE",
                "American Sniper", "Taken 3 ", "Avengers: Age of Ultron ",
                "John Wick ", "Guardians of the Galaxy ", "FURY", "Big Hero 6 ", "The Interview ",
                "Batman v Superman: Dawn of Justice ", "Ant-Man ",
                "The Equalizer ", "Blackhat ", "The Maze Runner ", "Chappie ", "Spectre ",
                "Predestination ", "Exodus: Gods and Kings ", "Furious 7 ", "Taken ", "Lucy",
                "Taken2", "Vice", "The Dark Knight", "The Avengers", "The Dark Knight Rises ",
                "Inception ", "How to Train Your Dragon 2 ", "Non-Stop", "Iron Man ", "The Incredibles",
                "Rush", "Run All Night", "Iron Man 2 ", "V for Vendetta ", "The Third Man",
                "Luara", "Chinatown", "Song One", "Baby", "The Drop", "The Awful Truth ", "Annie Hall", "nova", "sample"
                , "anna", "ann", "golden", "sky", "girl", "trip", "euro", "turkey", "boss", "key", "word", "summer"
                , "girls", "women", "man", "hangover", "hang", "sing", "song", "money", "event", "long",
                "short", "memory", "monitor", "message", "client", "movie", "Life", "monday", "sunday",
                "random", "title", "Brasil", "Broadcast", "brief", "camille", "dog", "cat", "euro trip",
                "chicken", "meat", "finger", "people", "family", "games", "forbidden", "police", "montana",
                "newyork", "from", "here", "cookies", "fortune", "teller", "action", "giant", "war",
                "gigi", "great", "hotel", "sex", "hair", "hamlet", "hunger games", "left behind", "Lone Survivor",
                "Robocop", "Pompeii", "horror", "kill", "Empire", "rise", "need", "for", "speed",
                "The Raid 2", "Captain", "Winter", "soldier", "Sabotage", "Sam", "Mansions", "Amazing", "Spider",
                "Hercules", "Guardians Of The Galaxy", "Last", "Metro", "Loving", "Love", "Star", "Star Wars", "The Departed ",
                "Memento", "American Beauty ", "Beauty", "Red", "Green", "Road", "Life", "Good", "Reservoir Dogs ",
                "black swan", "toy", "story", "Aliens ", "Casablanca ", "windows", "rear", "der", "Der Untergang",
                "Das Leben der Anderen", "Vertigo", "bonnie and Clyde", "The Fly ", "Roman Holiday", "kingsman", "secret"
                , "service", "wild", "obama", "Metascore", "change", "how", "difference", "live", "basket", "checkout",
                "killers", "momy", "army", "red", "blue", "spiner", "selma", "birdman", "fox", "price", "computer",
                " 61 Bullets", "The Vatican Museums", "Occupy the Farm",
                "Take It Easy", "Tevar", "Alone",
                "Crazy Cukkad Family", "Zed Plus", "Zid", "Action", "Ugly",
                "Finding Fanny", "Mary Kom", "9"
                , "10th Kingdom"
                , "12 Years a Slave"
                , "127 Hours"
                , "13 Going on 30"
                , "13th Warrior"
                , "1408"
                , "17 Again"
                , "1941"
                , "1969"
                , "20,000 Leagues Under the Sea"
                , "2001: A Space Odyssey"
                , "2012"
                , "2046"
                , "21 Grams"
                , "25th Hour"
                , "27 Dresses"
                , "28 Days Later"
                , "28 Weeks Later"
                , "3 Idiots"
                , "300"
                , "3000 Miles to Graceland"
                , "3:10 to Yuma"
                , "40 Year-Old Virgin"
                , "400 Blows"
                , "50/50"
                , "50 First Dates"
                , "(500) Days of Summer"
                , "7 Pounds"
                , "8 Mile"
                , "A[edit]"
                , "About Last Night..."
                , "About Schmidt"
                , "About Time"
                , "Abraham Lincoln: Vampire Hunter"
                , "Absence of Malice"
                , "Accidental Tourist"
                , "Accused"
                , "Ace Ventura: Pet Detective"
                , "Ace Ventura: When Nature Calls"
                , "Across the Universe"
                , "Adam's Rib"
                , "Addams Family"
                , "Adjustment Bureau"
                , "The Adventures of Pinocchio"
                , "Adventures of Robin Hood"
                , "The Affair of the Necklace"
                , "After Hours"
                , "After Sex"
                , "Aguirre, the Wrath of God"
                , "A.I. Artificial Intelligence"
                , "Air Bud"
                , "Air Force One"
                , "Airplane!"
                , "Airplane II: The Sequel"
                , "Airport"
                , "Airport 1975"
                , "Airport "
                , "Akeelah and the Bee"
                , "Akira"
                , "Aladdin"
                , "Aladdin and the King of Thieves"
                , "The Alamo"
                , "Albatross"
                , "Alexander"
                , "Alice Doesn't Live Here Anymore"
                , "Alice in Wonderland "
                , "Alien"
                , "Aliens"
                , "Alien 3"
                , "Alive"
                , "All About Steve"
                , "Almost Heroes"
                , "Alvin and the Chipmunks"
                , "Alvin and the Chipmunks: The Squeakquel"
                , "Alvin and the Chipmunks: Chipwrecked"
                , "All About Steve"
                , "All Dogs Go to Heaven"
                , "All Dogs Go to Heaven 2"
                , "All of Me"
                , "All the President's Men"
                , "All the Right Moves"
                , "Almost Famous"
                , "Along Came a Spider"
                , "Alpha Dog"
                , "Alpha and Omega"
                , "The Amazing Spider-Man "
                , "The Amityville Horror "
                , "American Beauty"
                , "American Chai"
                , "American Gangster"
                , "American Graffiti"
                , "American History X"
                , "American in Paris, An"
                , "American Me"
                , "American Pie"
                , "American Pie 2"
                , "American Pie Presents: The Book Of love"
                , "American Psycho"
                , "American Tail, An"
                , "American Tail: Fievel Goes West, An"
                , "An American Tail: The Treasure of Manhattan Island"
                , "American Wedding"
                , "Americanization of Emily"
                , "Amistad"
                , "Amour "
                , "Analyze This"
                , "Anastasia"
                , "Anchorman: The Legend of Ron Burgundy"
                , "...And Justice For All"
                , "And the Band Played On"
                , "Angel Eyes"
                , "Angel Heart"
                , "Angels & Demons"
                , "Angels in the Outfield"
                , "Angels with Dirty Faces"
                , "Angus, Thongs and Perfect Snogging"
                , "Animal House"
                , "Anna and the King"
                , "Anna Karenina"
                , "Annie"
                , "Annie Hall"
                , "Another Cinderella Story"
                , "Antitrust"
                , "Antz"
                , "Apocalypse Now"
                , "Apocalypto"
                , "Apollo 13"
                , "Are We Done Yet?"
                , "Are We There Yet?"
                , "Argo"
                , "Aristocats"
                , "Armageddon"
                , "Around the World in 80 Days "
                , "Arthur"
                , "As Good As It Gets"
                , "Assassination Games"
                , "Assassination of a High School President"
                , "At First Sight"
                , "Atlantic City"
                , "Atlantis: The Lost Empire"
                , "Atonement"
                , "Attack of the 50 Foot Woman"
                , "August Rush"
                , "Austin Powers: International Man of Mystery"
                , "Austin Powers: The Spy Who Shagged Me"
                , "Austin Powers in Goldmember"
                , "Avatar"
                , "The Avengers "
                , "Aviator"
                , "Away from Her"
                , "B[edit]"
                , "Babe"
                , "Babylon A.D"
                , "Bachelor Mother"
                , "Bachelorette"
                , "Backdraft"
                , "Back to the Future"
                , "Back to the Future Part II"
                , "Back to the Future Part III"
                , "Back to School"
                , "Bad and the Beautiful"
                , "Bad Boys"
                , "Bad Boys II"
                , "Bad Day at Black Rock"
                , "Bad Santa"
                , "Bad Taste"
                , "Badlands"
                , "Balto"
                , "Bambi"
                , "Bambi II"
                , "Bananas"
                , "Barbarella"
                , "Barcelona"
                , "Barton Fink"
                , "Barry Lyndon"
                , "BASEketball"
                , "Basic Instinct"
                , "Basic Instinct 2"
                , "Batman "
                , "Batman Begins"
                , "Batman Forever"
                , "Batman Returns"
                , "Battle: Los Angeles"
                , "Battle of San Pietro"
                , "Battle Royale"
                , "Beach"
                , "Beaches"
                , "Beast of Yucca Flats"
                , "Beasts of the Southern Wild"
                , "Beautiful Girls"
                , "Beautiful Mind, A"
                , "Beautiful Thing "
                , "Beauty and the Beast"
                , "Beavis and Butthead Do America"
                , "Becoming Jane"
                , "Bedazzled "
                , "Bedazzled "
                , "Bedknobs and Broomsticks"
                , "Bedtime Stories"
                , "Bee Movie"
                , "Bee Season"
                , "Beerfest"
                , "Beetlejuice"
                , "Before Midnight"
                , "Before Sunrise"
                , "Before Sunset"
                , "Beginners"
                , "Behind Enemy Lines"
                , "Being John Malkovich"
                , "Being There"
                , "Be Kind Rewind"
                , "Believer"
                , "Ben-Hur"
                , "Bend It Like Beckham"
                , "Benny & Joon"
                , "Beowulf"
                , "Best Little Whorehouse in Texas"
                , "Best in Show"
                , "Best Years of Our Lives"
                , "Better Off Dead"
                , "Better Than Chocolate"
                , "Better Tomorrow, A"
                , "Beverly Hills Chihuahua"
                , "Beverly Hills Cop II"
                , "Beverly Hills Cop III"
                , "Beyond the Valley of the Dolls"
                , "Bicentennial Man"
                , "Bicycle Thieves"
                , "Big"
                , "Big Chill"
                , "Big Daddy"
                , "Big Easy"
                , "Big Fat Liar"
                , "Big Fish"
                , "Big Lebowski"
                , "Big Night"
                , "Big Sleep"
                , "Big Top Pee-wee"
                , "Big Trouble"
                , "Big Trouble in Little China"
                , "Bill and Ted's Excellent Adventure"
                , "Billy Madison"
                , "Birds"
                , "Birdman"
                , "Black Book"
                , "Black Cat"
                , "Black Christmas"
                , "Black Christmas"
                , "Black Hawk Down"
                , "Black Hole"
                , "Black Rain"
                , "Black Sheep"
                , "Black Swan"
                , "Blade"
                , "Blade II"
                , "Blade: Trinity"
                , "Blade Runner"
                , "Blades of Glory"
                , "Blair Witch Project"
                , "Blind Date"
                , "Blazing Saddles"
                , "Blood Diamond"
                , "Blood Feast"
                , "Blood Simple"
                , "Blow"
                , "Blown Away"
                , "Blue Collar"
                , "Blue Jasmine"
                , "Blue Velvet"
                , "Blue Lagoon"
                , "Blues Brothers"
                , "Body Heat"
                , "Body of Lies"
                , "Boiler Room"
                , "Bolt"
                , "Boogeyman"
                , "Book of Life"
                , "Book of Pooh: Stories from the Heart"
                , "Book of Shadows: Blair Witch 2"
                , "Book Thief"
                , "Boondock Saints"
                , "orat: Cultural Learnings of America for Make Benefit Glorious Nation "
                , "Born on the Fourth of July"
                , "Bottle Rocket"
                , "Bound"
                , "Bourne Identity"
                , "Bourne Legacy"
                , "Bourne Supremacy"
                , "Bourne Ultimatum"
                , "Bowling for Columbine"
                , "Boy Named Charlie Brown, A"
                , "Boyhood"
                , "Boys from Brazil"
                , "Boys Town"
                , "Boyz n the Hood"
                , "Braindead"
                , "Brassed Off"
                , "Brave"
                , "Braveheart"
                , "Brazil"
                , "Breakfast at Tiffany's"
                , "Breakfast Club"
                , "Breaking Away"
                , "Breaking Up"
                , "Brian's Song"
                , "Bride Wars"
                , "Bridge on the River Kwai, "
                , "Bridge to Terabithia"
                , "Bridget Jones's Diary"
                , "Bring It On"
                , "Bringing Up Baby"
                , "Broadcast News"
                , "Brokeback Mountain"
                , "Broken Arrow"
                , "Bronx Tale, A"
                , "Brother Bear"
                , "Brother Bear 2"
                , "Brothers Grimm, "
                , "Brothers McMullen, "
                , "Brothers Solomon, "
                , "Brubaker"
                , "Bruce Almighty"
                , "Buckaroo Banzai"
                , "Bucket List, "
                , "Buffalo 66"
                , "Buffy the Vampire Slayer"
                , "Bug"
                , "Bug's Life, A"
                , "Bull Durham"
                , "Bullitt"
                , "Burn After Reading"
                , "But I'm a Cheerleader"
                , "Butch Cassidy and the Sundance Kid"
                , "Butterfly Effect, "
                , "By Dawn's Early Light"
                , "C[edit]"
                , "Cabin in the Woods, "
                , "Cabinet of Dr. Caligari, "
                , "Cable Guy, The"
                , "Caddyshack"
                , "Caine Mutiny, "
                , "Camelot"
                , "Camille "
                , "Camp Rock"
                , "Can't Buy Me Love"
                , "Can't Hardly Wait"
                , "Candy"
                , "Cape Fear"
                , "Capricorn One"
                , "Captain America: The First Avenger"
                , "Captain America: The Winter Soldier"
                , "Captain Phillips"
                , "Care Bears Movie, The"
                , "Care Bears Movie II: A New Generation"
                , "Carlito's Way"
                , "Carnal Knowledge"
                , "Carrie "
                , "Cars"
                , "Cars 2"
                , "Casablanca"
                , "Casanova"
                , "Casino"
                , "Casino Royale"
                , "Cast Away"
                , "Casualties of War"
                , "Catch-22"
                , "Catch Me If You Can"
                , "Cat on a Hot Tin Roof"
                , "Cat People"
                , "Cat Returns, The"
                , "Cats & Dogs"
                , "Cats & Dogs: The Revenge of Kitty Galore"
                , "Cats Don't Dance"
                , "Catwoman"
                , "Cecil B. Demented"
                , "Changing Lanes"
                , "harlie and the Chocolate Factory"
                , "Charlie's Angels"
                , "Charlie's Angels: Full Throttle"
                , "Charlie Wilson's War"
                , "Chariots of Fire"
                , "Charlotte's Web"
                , "Chasing Amy"
                , "Chasing Liberty"
                , "Cheaper by the Dozen (2003)"
                , "Cheech & Chong's Next Movie"
                , "Chicago"
                , "Chicken Run"
                , "Children of Dune"
                , "Children of Men"
                , "Children of Paradise"
                , "Children's Hour, The"
                , "Child's Play"
                , "Chinatown"
                , "Chitty Chitty Bang Bang"
                , "Chloe"
                , "Chocolat"
                , "Choke"
                , "Christmas Story, A"
                , "Christmas with the Kranks"
                , "The Chronicles of Narnia: Prince Caspian"
                , "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe"
                , "The Chronicles of Narnia: The Voyage of the Dawn Treader"
                , "Chronicles of Riddick, The"
                , "Chumscrubber, The"
                , "Chungking Express"
                , "Cider House Rules, The"
                , "Cinderella "
                , "A Cinderella Story"
                , "Citizen Kane"
                , "City of Angels"
                , "City of Ember"
                , "City on Fire"
                , "City of God"
                , "City Slickers"
                , "Clash of the Titans "
                , "Clear and Present Danger"
                , "Cleopatra "
                , "Click"
                , "Client, The"
                , "Clerks"
                , "Clerks II"
                , "Clockwise"
                , "Clockwork Orange, A"
                , "Close Encounters Of The Third Kind"
                , "Closer"
                , "Cloudy with a Chance of Meatballs"
                , "Cloverfield"
                , "Clue"
                , "Clueless"
                , "Coach Carter"
                , "Cocktail"
                , "Color Purple, The"
                , "Cold Mountain"
                , "Collateral"
                , "Coming Home"
                , "Commando"
                , "Commitments, The"
                , "Compulsion"
                , "Con Air"
                , "Conan the Barbarian"
                , "Conan the Destroyer "
                , "Coneheads"
                , "Confessions of a Dangerous Mind"
                , "Confetti"
                , "Conquest of Space"
                , "Conspiracy Theory"
                , "Constant Gardener, The"
                , "Cool and the Crazy‎"
                , "Cool Hand Luke"
                , "Cool Runnings"
                , "Cool World"
                , "Coraline"
                , "Core, The"
                , "Corpse Bride"
                , "Contact"
                , "Court Jester, The"
                , "Count of Monte Cristo, The"
                , "Cowboy Bebop: The Movie"
                , "Coyote Ugly"
                , "Craft, The"
                , "Crank"
                , "Crash"
                , "Crimes and Misdemeanors"
                , "Crimewave"
                , "Crimson Tide"
                , "Criss Cross"
                , "Crocodile Dundee"
                , "The Croods"
                , "Cross of Iron"
                , "Crouching Tiger, Hidden Dragon"
                , "Cry Freedom"
                , "Cry Wolf"
                , "Crow"
                , "Cruel Intentions"
                , "Crying Game"
                , "Cube"
                , "Cube 2: Hypercube"
                , "Cube Zero"
                , "Cure"
                , "The Curious Case of Benjamin Button"
                , "Cursed"
                , "Cutting Edge"
                , "D[edit]"
                , "Da Vinci Code"
                , "Daddy Day Camp"
                , "Daddy Day Care"
                , "Dallas Buyers Club"
                , "Dan in Real Life"
                , "Dance of the Dead"
                , "Dancer In The Dark"
                , "Dances with Wolves"
                , "Dangerous Beauty"
                , "Daredevil"
                , "Darjeeling Limited"
                , "Dark City"
                , "Dark Knight"
                , "Dark Knight Rises"
                , "Dark Passage"
                , "Das Boot"
                , "Das Leben der Anderen"
                , "Dave"
                , "Dawn of the Dead "
                , "Day After Tomorrow"
                , "Day at the Races, A"
                , "Day of the Jackal"
                , "The Day the Earth Stood Still"
                , "Daydream Nation"
                , "Days of Being Wild"
                , "Days of Thunder"
                , "Dazed and Confused"
                , "Dead Alive"
                , "Dead Man Walking"
                , "Dead Poets Society"
                , "Deadfall"
                , "Death Becomes Her"
                , "Death Rides a Horse"
                , "Death to Smoochy"
                , "Death Wish (I-V)"
                , "D.E.B.S."
                , "Dedication"
                , "Deep Impact"
                , "Deep Throat"
                , "Deer Hunter"
                , "Deewar"
                , "Defending Your Life"
                , "Defendor"
                , "Déjà Vu"
                , "Deliverance"
                , "Departed"
                , "Der Fuehrer's Face"
                , "Descendants"
                , "Descent"
                , "Desperate Living"
                , "Despicable Me"
                , "Despicable Me 2"
                , "Destry Rides Again"
                , "Deuce Bigalow: European Gigolo"
                , "Deuce Bigalow: Male Gigolo"
                , "Devil's Advocate"
                , "Devil's Own"
                , "Devil's Rejects"
                , "Devil in a Blue Dress"
                , "Devil Wears Prada"
                , "Defiance "
                , "Dial M for Murder"
                , "Diary of a Wimpy Kid"
                , "Diamonds Are Forever"
                , "Dick"
                , "Dick Tracy"
                , "Die Hard"
                , "Die Hard 2: Die Harder"
                , "Die Hard With a Vengeance"
                , "Live Free or Die Hard"
                , "Dinosaur"
                , "Dirty Dancing"
                , "Dirty Harry"
                , "Dirty Rotten Scoundrels"
                , "Dirty Shame, A"
                , "Disaster Movie"
                , "Disclosure"
                , "District 9"
                , "Disturbia"
                , "Disturbing Behavior"
                , "Divergent"
                , "Divine Secrets of the Ya Ya Sisterhood"
                , "Doctor Dolittle "
                , "Dr. Dolittle 2"
                , "Doctor Zhivago"
                , "Dodgeball: A True Underdog Story"
                , "Dodsworth"
                , "Dogma"
                , "Dogville"
                , "Dog Day Afternoon"
                , "Dolores Claiborne"
                , "Don Jon"
                , "Don Juan DeMarco"
                , "Donald in Mathmagic Land"
                , "Donnie Brasco"
                , "Donnie Darko"
                , "on't Be A Menace To South Central While Drinking Your Juice In The Hood"
                , "Don't Say a Word"
                , "Don't Tell Mom the Babysitter's Dead"
                , "Doom"
                , "Doors, The"
                , "Dorian Gray"
                , "Double Indemnity"
                , "Down Periscope"
                , "Down to Earth"
                , "Down With Love"
                , "Dr. No"
                , "Dr. Strangelove: Or How I Learned to Stop Worrying and Love the Bomb"
                , "Dracula "
                , "Dracula: Dead and Loving It"
                , "Dragnet"
                , "Dreamers"
                , "Driving Miss Daisy"
                , "Drop Dead Fred"
                , "Drop Dead Gorgeous"
                , "Drowning Mona"
                , "Drugstore Cowboy"
                , "Duck Soup"
                , "Dude, Where's My Car?"
                , "Duel"
                , "Duel in the Sun"
                , "Dukes of Hazzard"
                , "Dumb and Dumber"
                , "Dumb and Dumberer"
                , "Dumbo"
                , "Dummy"
                , "Dune"
                , "Duplex"
                , "Dylan Dog: Dead of Night"
                , "E[edit]"
                , "Earthquake"
                , "East of Eden"
                , "Eastern Promises"
                , "Easy Rider"
                , "Ed Wood"
                , "Eddie and the Cruisers"
                , "Edge, The"
                , "Education, An"
                , "Edward Scissorhands"
                , "Eight Crazy Nights"
                , "Eight Legged Freaks"
                , "Eight Men Out"
                , "Election"
                , "Elf"
                , "Elizabeth"
                , "Elizabethtown"
                , "Elmer Gantry"
                , "Emperor's New Groove"
                , "Empire Records"
                , "Enchanted"
                , "End of Days"
                , "Enemy at the Gates"
                , "Enemy of the State"
                , "Englishman Who Went Up a Hill But Came Down a Mountain"
                , "English Patient"
                , "Enter the Dragon"
                , "Epic"
                , "Epic Movie"
                , "Equilibrium"
                , "Eragon"
                , "Erin Brockovich"
                , "Elvis"
                , "Ernest Goes to Camp"
                , "Ernest Goes to Jail"
                , "Ernest Saves Christmas"
                , "Ernest Scared Stupid"
                , "Escape from New York"
                , "E.T. the Extra-Terrestrial"
                , "Eternal Sunshine of the Spotless Mind"
                , "Eurotrip"
                , "Evan Almighty"
                , "Event Horizon"
                , "Ever After"
                , "Everything Is Illuminated"
                , "Evil Dead"
                , "Evil Dead 2"
                , "Evolution"
                , "Excalibur"
                , "Exorcist"
                , "Exorcist III"
                , "Expelled: No Intelligence Allowed"
                , "An Extremely Goofy Movie"
                , "Eyes Wide Shut"
                , "F[edit]"
                , "Face in the Crowd, A"
                , "Face/Off"
                , "Factory Girl"
                , "Fahrenheit 451"
                , "Fahrenheit 9/11"
                , "Fail-Safe"
                , "Failure to Launch"
                , "Falling Down"
                , "Fame"
                , "Family Man"
                , "Fantastic Four"
                , "Fargo"
                , "Fast and Furious"
                , "Fast and Furious 6"
                , "Fast and the Furious"
                , "Fast and the Furious: Tokyo Drift"
                , "Fast, Cheap and Out of Control"
                , "Fast Five"
                , "Fast Times at Ridgemont High"
                , "Faster, Pussycat! Kill! Kill!"
                , "Fat Albert"
                , "Father of the Bride "
                , "Fear and Loathing in Las Vegas"
                , "Fearless"
                , "Femme Fatale"
                , "FernGully: The Last Rainforest"
                , "Ferris Bueller's Day Off"
                , "Few Good Men, A"
                , "Fiddler on the Roof"
                , "Field of Dreams"
                , "Fifth Element, The"
                , "Fight Club"
                , "Fighter, The"
                , "Final Destination"
                , "Final Destination 2"
                , "Final Destination 3"
                , "The Final Destination"
                , "Final Destination 5"
                , "Final Fantasy: The Spirits Within"
                , "Final Fantasy VII: Advent Children"
                , "Finding Forrester"
                , "Finding Nemo"
                , "Finding Neverland"
                , "Fine Mess, A"
                , "Firm, The"
                , "First Blood"
                , "First Knight"
                , "First Wives Club, The"
                , "Fish Called Wanda, A"
                , "Fisher King, The"
                , "Fistful of Dollars, A"
                , "Five Easy Pieces"
                , "Five Minutes of Heaven"
                , "Flags of Our Fathers"
                , "Flash Gordon"
                , "Flatliners"
                , "Fletch"
                , "Fletch Lives aka Fletch 2"
                , "Flicka"
                , "Flipper "
                , "Flubber"
                , "Flushed Away"
                , "Flyboys"
                , "Fog of War, "
                , "Football Factory, "
                , "Footloose (2011)"
                , "Forbidden Kingdom, "
                , "Forgetting Sarah Marshall"
                , "Forrest Gump"
                , "Fortune Cookie, "
                , "Four Brothers"
                , "Four Weddings And A Funeral"
                , "Fountainhead, "
                , "Fox and the Hound, "
                , "The Fox and the Hound 2"
                , "Frankenstein "
                , "Fracture"
                , "Frailty"
                , "Freaky Friday "
                , "Freddy Got Fingered"
                , "Freddy vs. Jason"
                , "Free Willy"
                , "French Connection, "
                , "Frenzy"
                , "Friday "
                , "Friday Night Lights"
                , "Fried Green Tomatoes"
                , "Friends of Eddie Coyle, "
                , "Friendly Persuasion"
                , "Fritz the Cat"
                , "From Dusk till Dawn"
                , "From Hell"
                , "From Here to Eternity"
                , "From Russia with Love"
                , "Frost/Nixon"
                , "Frozen (2013)"
                , "Fuck"
                , "Fugitive, "
                , "Full Metal Jacket"
                , "Galaxy Quest"
                , "Game 6"
                , "Game, "
                , "Game Plan, "
                , "Gandhi"
                , "Gangs of New York"
                , "Garden State"
                , "Garfield"
                , "Gaslight"
                , "Gates of Heaven"
                , "Gattaca"
                , "Gentleman Prefer Blondes"
                , "George of the Jungle"
                , "Georgia Rule"
                , "Get Carter"
                , "Gettysburg"
                , "Get Shorty"
                , "Ghostbusters"
                , "Ghostbusters II"
                , "Ghost Dog: The Way of the Samurai"
                , "Ghost in the Shell 2: Innocence"
                , "Ghost Rider"
                , "Ghosts"
                , "Ghost World"
                , "G.I. Jane"
                , "G.I. Joe: Retaliation"
                , "Giant Claw, "
                , "Girl, Interrupted"
                , "Girl Next Door, "
                , "Girls Will Be Girls"
                , "Gladiator"
                , "Glen or Glenda"
                , "Glengarry Glen Ross"
                , "Glory"
                , "Glory Road"
                , "Gnomeo and Juliet"
                , "Godfather"
                , "Gods Must Be Crazy, "
                , "Gone Baby Gone"
                , "Gone in 60 seconds"
                , "Gone with the Wind"
                , "Good Girl, The"
                , "Good Burger"
                , "Goodbye Girl, "
                , "Good Bye Lenin!"
                , "Goodfellas"
                , "Good Luck Chuck"
                , "Good Morning, Vietnam"
                , "Good Night, and Good Luck."
                , "Good Son, "
                , "Good Will Hunting"
                , "Good Year"
                , "Good, the Bad and the Ugly, "
                , "Goofy Movie"
                , "Goonies, "
                , "Gosford Park"
                , "Gotti"
                , "Graduate, "
                , "The Grand Budapest Hotel"
                , "Grand Canyon"
                , "Grand Hotel"
                , "Grand Voyage, Le"
                , "Grandma's Boy"
                , "Grapes of Wrath,  "
                , "Gravity"
                , "Great Dictator, "
                , "Great Expectations"
                , "Grease"
                , "Grease 2"
                , "Great Debaters, "
                , "Great Escape, "
                , "The Great Mouse Detective"
                , "The Great Outdoors"
                , "The Greatest Game Ever Played"
                , "Green for Danger"
                , "Green Lantern"
                , "Green Mile, "
                , "Green Zone"
                , "Greenberg"
                , "Gremlins"
                , "Grey Zone, "
                , "Grifters, "
                , "Grindhouse"
                , "Groundhog Day"
                , "Grosse Pointe Blank"
                , "Grown Ups"
                , "Grumpy Old Men"
                , "Guardians of the Galaxy"
                , "Guarding Tess"
                , "Guess Who"
                , "Guess Who's Coming to Dinner"
                , "Gun Crazy"
                , "Gung Ho", "The Pacifier"
                , "Pacific Rim"
                , "Pagemaster, The"
                , "Paparazzi"
                , "Paper Chase, The"
                , "Paradine Case, The"
                , "Parallax View, The"
                , "Parenthood"
                , "Party, The"
                , "Party Monster"
                , "Passion of the Christ, The"
                , "Patch Adams"
                , "Paths of Glory"
                , "Patriot, The"
                , "Patriot Games"
                , "Patton"
                , "Paul Blart: Mall Cop"
                , "The Pawnbroker"
                , "Pay It Forward"
                , "Paycheck"
                , "PCU"
                , "Peaceful Warrior"
                , "Peacemaker, The"
                , "The Pebble and the Penguin"
                , "Pee-wee's Big Adventure"
                , "Peggy Sue Got Married"
                , "Pelican Brief, The"
                , "H[edit]"
                , "Hackers"
                , "Hair"
                , "Hairspray"
                , "Halloween"
                , "Rob Zombie's Halloween"
                , "Halloween II "
                , "Half Baked"
                , "Hamlet 2"
                , "Hammett"
                , "Hancock"
                , "Hangover, "
                , "The Hangover: Part II"
                , "Hannah and Her Sisters"
                , "Hannah Montana: The Movie"
                , "Hannibal"
                , "Hannibal Rising"
                , "Happening, "
                , "Happy Feet"
                , "Happy Feet Two"
                , "Happy Gilmore"
                , "Hard Boiled"
                , "Hard Candy"
                , "Hard Eight"
                , "Here Comes Pupcake"
                , "Hard Day's Night, A"
                , "Harold & Kumar Go to White Castle"
                , "Harold & Kumar Escape from Guantanamo Bay"
                , "Harold and Maude"
                , "Harry Potter and the Sorcerer's Stone"
                , "Harry Potter and the Chamber of Secrets"
                , "Harry Potter and the Prisoner of Azkaban"
                , "Harry Potter and the Goblet of Fire"
                , "Harry Potter and the Order of the Phoenix"
                , "Harry Potter and the Half-Blood Prince"
                , "Harry Potter and the Deathly Hallows – Part 1"
                , "Harry Potter and the Deathly Hallows – Part 2"
                , "Harvey"
                , "He's Just Not That Into You"
                , "He Died With A Felafel In His Hand"
                , "Heat"
                , "Heartbreak Ridge"
                , "Heathers"
                , "Heavy Traffic‎"
                , "Heavyweights"
                , "Heist"
                , "Hellboy"
                , "Hellboy II: The Golden Army"
                , "Hellraiser"
                , "Hellbound: Hellraiser II"
                , "Hellraiser III: Hell on Earth"
                , "Hellraiser: Bloodline"
                , "Hellraiser: Inferno"
                , "Hellraiser: Hellseeker"
                , "Hellraiser: Deader"
                , "Hellraiser: Hellworld"
                , "Help!"
                , "Her"
                , "Herbie: Fully Loaded"
                , "Herbie Goes Bananas"
                , "Herbie Goes to Monte Carlo"
                , "Herbie Rides Again"
                , "Hero"
                , "Hey Good Lookin'"
                , "Hide and Seek"
                , "High Fidelity"
                , "High Noon"
                , "Highlander (series)"
                , "High School Musical"
                , "High School Musical 2"
                , "High School Musical 3"
                , "High Road To China"
                , "The Hills Have Eyes 2"
                , "His Girl Friday"
                , "History Boys"
                , "History of the World: Part I"
                , "History of Violence, A"
                , "Hitch"
                , "Hitchhiker's Guide to the Galaxy, "
                , "Hobbit: An Unexpected Journey, "
                , "Hobbit: The Desolation of Smaug, "
                , "Holes"
                , "The Holiday"
                , "Holiday Inn"
                , "Hollywood Homicide"
                , "Hollywood Shuffle"
                , "Home Alone"
                , "Home Alone 2: Lost in New York"
                , "Home Alone 3"
                , "Home Alone 4"
                , "Home for the Holidays"
                , "Homeward Bound: The Incredible Journey"
                , "Homeward Bound II: Lost in San Francisco"
                , "Honey, I Shrunk The Kids"
                , "Honeymoon in Vegas"
                , "Hoodwinked"
                , "Hook"
                , "Hoosiers"
                , "Horror Express"
                , "Horse Feathers"
                , "Hospital, "
                , "Hostel"
                , "Hostel: Part II"
                , "Hotel Rwanda"
                , "Hot Chick, "
                , "Hot Fuzz"
                , "Hot Rod"
                , "Hot Shots! Part Deux"
                , "Hot Shots"
                , "Hours, "
                , "The House Bunny"
                , "House on Haunted Hill"
                , "How Green Was My Valley"
                , "How to Lose a Guy in 10 Days"
                , "How to Train Your Dragon"
                , "How to Train Your Dragon 2"
                , "Howard the Duck"
                , "Howl's Moving Castle"
                , "Howling, The"
                , "Hud"
                , "Hudsucker Proxy, "
                , "Human Traffic"
                , "The Hunchback of Notre Dame "
                , "The Hunger Games"
                , "Hunt for Red October, "
                , "Hurricane,  "
                , "Hurt Locker, "
                , "Hustler, "
                , "I[edit]"
                , "I Am a Fugitive from a Chain Gang"
                , "I Am Legend"
                , "I Am Sam"
                , "I Heart Huckabees"
                , "I Know What You Did Last Summer"
                , "I Love You, Man"
                , "I Now Pronounce You Chuck and Larry"
                , "I, Robot"
                , "I Still Know What You Did Last Summer"
                , "Ice Age"
                , "Ice Age: The Meltdown"
                , "Ice Age: Dawn of the Dinosaurs"
                , "Ice Age: Continental Drift"
                , "Ice Princess"
                , "Ides of March, "
                , "Idiocracy"
                , "If Only"
                , "Ikiru"
                , "Il Postino"
                , "Illusionist, "
                , "Imagine Me & You"
                , "I'm No Angel"
                , "I'm Not There"
                , "Imitation Game, "
                , "Impossible"
                , "In & Out"
                , "In a Lonely Place"
                , "In Bruges"
                , "In Cold Blood"
                , "In the Heat of the Night"
                , "In the Line of Fire"
                , "In The Loop"
                , "Incredible Hulk, "
                , "In Her Shoes"
                , "In the Mood for Love"
                , "In the Name of the Father"
                , "Into the Blue"
                , "Into the Wild"
                , "Inception"
                , "Incredibles, "
                , "Inconvenient Truth, An"
                , "Independence Day"
                , "Inferno"
                , "Indiana Jones and the Kingdom of the Crystal Skull"
                , "Indiana Jones and the Last Crusade"
                , "Indiana Jones and the Temple of Doom"
                , "Inglorious Basterds"
                , "Innerspace"
                , "Inside Man"
                , "Inside Monkey Zetterland"
                , "Inspector Gadget"
                , "Inspector Gadget 2"
                , "Interview with the Vampire"
                , "Intolerable Cruelty"
                , "Invasion of the Body Snatchers "
                , "Inventing the Abbotts"
                , "Invictus"
                , "Iron Man"
                , "Iron Man 2"
                , "Iron Man 3"
                , "Iron Giant, "
                , "Iron Jawed Angels"
                , "Island, "
                , "Island of Dr. Moreau,  "
                , "It's a Wonderful Life"
                , "It's a Mad, Mad, Mad, Mad World"
                , "It"
                , "It Conquered the World"
                , "It Happened One Night"
                , "Italian Job"
                , "Jack"
                , "Jacket"
                , "Jackie Brown"
                , "Jacob's Ladder"
                , "Jagged Edge"
                , "James and the Giant Peach"
                , "James Bond series"
                , "Jarhead"
                , "Jaws"
                , "Jaws 2"
                , "Jaws 3-D"
                , "Jay and Silent Bob Strike Back"
                , "Jeepers Creepers"
                , "Jennifer's Body"
                , "Jeremiah Johnson"
                , "Jerk"
                , "Jerry Maguire"
                , "JFK"
                , "Joe's Apartment"
                , "Joe Dirt"
                , "Joe Versus the Volcano"
                , "Joseph: King of Dreams"
                , "Joshua Tree "
                , "Johnny Dangerously"
                , "Johnny English"
                , "John Tucker Must Die"
                , "Josie and the Pussycats"
                , "Jude"
                , "Judgment at Nuremberg"
                , "Jumanji"
                , "Jumper"
                , "Junebug"
                , "Jungle 2 Jungle"
                , "Jungle Book, "
                , "Jungle Book 2, "
                , "Jurassic Park"
                , "Jurassic Park: The Lost World"
                , "Jurassic Park 3"
                , "Just Friends"
                , "Just Like Heaven"
                , "Juwanna Mann"
                , "K[edit]"
                , "K-PAX"
                , "Kagemusha"
                , "Kalifornia"
                , "Kangaroo Jack"
                , "Karate Kid"
                , "Karate Kid, Part II"
                , "Karate Kid, Part III"
                , "Kate & Leopold"
                , "Kelly's Heroes"
                , "Kentucky Fried Movie"
                , "Key Largo"
                , "Khuda Kay Liye"
                , "Kicking & Screaming"
                , "Kicking and Screaming"
                , "Kids Are All Right"
                , "Kill Bill: Volume 1"
                , "Kill Bill: Volume 2"
                , "Killer Klowns from Outer Space"
                , "Killers,"
                , "Killer Inside Me"
                , "Killing Fields"
                , "Kindergarten Cop"
                , "Kind Hearts and Coronets"
                , "King Arthur"
                , "King Kong "
                , "King's Speech"
                , "Kingdom of Heaven"
                , "Kingpin"
                , "Kinsey"
                , "Kiss Before Dying, A"
                , "Kiss Kiss Bang Bang"
                , "Kiss Me Deadly"
                , "Kiss Tomorrow Goodbye"
                , "Kite Runner"
                , "Klute"
                , "Knight and Day"
                , "Knight's Tale, A"
                , "Knocked Up"
                , "Knute Rockne, All American"
                , "Kramer vs. Kramer"
                , "Kung Fu Hustle"
                , "Kung Fu Panda"
                , "Kung Fu Panda 2"
                , "Kung Pow! Enter the Fist"
                , "L[edit]"
                , "L. A. Confidential"
                , "La lengua de las mariposas"
                , "Labyrinth"
                , "Ladder 49"
                , "Lady and the Tramp"
                , "Lady and the Tramp II: Scamp's Adventure"
                , "Ladies Man, The"
                , "Lady Eve, The"
                , "Lady in the Water"
                , "Lady Vanishes"
                , "Land of the Dead"
                , "Lara Croft: Tomb Raider"
                , "Lara Croft Tomb Raider: The Cradle of Life"
                , "L. A. Story"
                , "Last Action Hero"
                , "Last Boy Scout"
                , "Last Days of Disco"
                , "Last Detail"
                , "The Last House on the Left "
                , "Last Man on Earth"
                , "The Last Mimzy"
                , "Last of the Mohicans"
                , "Last Picture Show"
                , "Last Samurai"
                , "Last Seduction"
                , "Last Starfighter"
                , "Laura"
                , "Latter Days"
                , "Lavender Hill Mob"
                , "Law Abiding Citizen"
                , "Lawrence of Arabia"
                , "Layer Cake"
                , "Legally Blonde"
                , "Legally Blonde 2: Red, White and Blonde"
                , "Lean on Me"
                , "League of Extraordinary Gentlemen"
                , "League of Their Own, A"
                , "Leaving Las Vegas"

        };
        int getMoviesLength = movies.length;
        randomMovie = movies[random.nextInt(getMoviesLength)];

        return randomMovie;


    }
}
